### ISSUE TITLE
Feature request: OPDS support

### ISSUE THREAD

**Issue by knutov** [CrazyCoder/coolreader-kindle-qt#5]
Are there any plans to add OPDS support to this port of CoolReader?

**Comment by CrazyCoder** [comment]
While this feature may be useful, I don't think I'll be interested in implementing it. I don't use OPDS myself.

**Comment by knutov** [comment]
Is it hard to implement? I'm thinking about sponsor this.

I did not use it for the years, but now found it very convenient (on android) to get recently translated books from series without using cables.

**Comment by CrazyCoder** [comment]
Plenty of UI work is required, even if some library is used for the OPDS logic. UI needs to work well with navigation keys and touchscreen. Considering there is no virtual keyboard, it would be hard to search for books.

Very time consuming and boring to implement.

**Comment by knutov** [comment]
Well, looks like it's really better to forget about it.

**Comment by HLFH** [comment]
Forget OPDS ? It's a must-have :(
