### ISSUE TITLE
Highlights and their export to a file support

### ISSUE THREAD

**Issue by mergen3107** [CrazyCoder/coolreader-kindle-qt#8]
Are there any plans to implement those features (including for Kindle 4?)

Thank you!

**Comment by CrazyCoder** [comment]
I don't plan to continue working on this project. There is another maintainer for the similar project, you may submit your requests there:

http://kobo_coolreader.reformal.ru/
http://wiki.vlasovsoft.net/doku.php?id=ru:coolreader

**Comment by mergen3107** [comment]
@CrazyCoder 
Thank you so much! I never seen the first website
